import os
from pathlib import Path
from fpdf import FPDF
from matplotlib import pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import psycopg2
import seaborn as sns
from io import BytesIO
from fpdf.enums import XPos, YPos

# Import your individual Python scripts
from scripts.Scouting_Report_Template_Configuration.processing.Hitter_Season_Stats import generate_hitter_season_stats_visual
from scripts.Scouting_Report_Template_Configuration.processing.Hitter_Splits_Against_Pitcher_Arsenal import generate_hitter_splits_visual
from scripts.Scouting_Report_Template_Configuration.processing.Pitch_Arsenal_Visualization import generate_pitch_arsenal_visual
from scripts.Scouting_Report_Template_Configuration.processing.Pitcher_Heatmap import generate_pitcher_heatmap_visual
from scripts.Scouting_Report_Template_Configuration.processing.Season_Stats_Pitcher_Viz import generate_season_stats_viz

# Database configuration
DB_CONFIG = {
    "host": "aws-0-us-east-2.pooler.supabase.com",
    "database": "postgres",
    "user": "postgres.chcovbrcpmlxyauansqe",
    "password": "1Z4IO6fxxYw8PgxL",  # Replace with your Supabase password
    "port": 5432
}

def figure_to_image(fig):

    buf = BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', pad_inches=0)
    buf.seek(0)
    return buf

def fetch_player_name(player_id):
    query = """
    SELECT CONCAT("First_Name", ' ', "Last_Name") AS player_name
    FROM players
    WHERE key_mlbam = %s;
    """
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        cursor = conn.cursor()
        cursor.execute(query, (player_id,))
        result = cursor.fetchone()
        cursor.close()
        conn.close()
        return result[0] if result else None
    except Exception as e:
        print(f"Error fetching player name: {e}")
        return None

def create_title_page(hitter_name, pitcher_name):
    fig, ax = plt.subplots(figsize=(8.5, 11))
    ax.axis('off')
    title = f"Scouting Report: {hitter_name} vs. {pitcher_name}"
    ax.text(0.5, 0.7, title, fontsize=24, ha='center', va='center', wrap=True)
    ax.text(0.5, 0.5, "Generated by Baseball MVP System", fontsize=14, ha='center', va='center', alpha=0.7)
    return fig


def generate_scouting_report(hitter_name, pitcher_name, visuals, pdf_path):
    """
    Generate the scouting report PDF without section titles.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title Page
    pdf.set_font("Helvetica", size=16)
    pdf.cell(200, 10, text=f"Scouting Report: {hitter_name} vs. {pitcher_name}", align='C')
    pdf.ln(10)

    # Layout settings
    page_width = 190  # Approximate width of the page in FPDF
    full_width = page_width - 20  # Full-width visuals
    half_width = (page_width - 30) / 2  # Side-by-side visuals
    section_height = 50  # Adjusted height for full-width sections
    small_section_height = 50  # Adjusted height for side-by-side visuals

    # Add visuals in the specified order
    layout_order = [
        visuals.get("Hitter Season Stats"),
        visuals.get("Pitcher Season Stats"),
        visuals.get("Hitter Splits Against Arsenal"),
        visuals.get("Pitcher Arsenal"),
        visuals.get("Pitcher Heatmap"),
    ]

    for idx, visual in enumerate(layout_order):
        # Determine position for side-by-side visuals
        if idx == 2:  # Hitter Splits Against Arsenal (left)
            x, y = 10, pdf.get_y()
        elif idx == 3:  # Pitch Usage Rate (right)
            x, y = page_width / 2 + 5, pdf.get_y()  # Align with the previous section
        else:
            x, y = 10, pdf.get_y()  # Default full-width visuals

        # Embed visual
        if isinstance(visual, plt.Figure):  # Handle Matplotlib figures
            img_buf = figure_to_image(visual)
            pdf.image(img_buf, x=x, y=y, w=full_width if idx < 2 or idx == 4 else half_width, h=section_height)

        # Adjust Y-position for side-by-side or full-width visuals
        if idx in [2, 3]:  # After both side-by-side visuals, reset the y-position
            if idx == 3:  # Second side-by-side visual
                pdf.ln(small_section_height)
        else:
            pdf.ln(section_height)

    # Save the PDF
    pdf.output(pdf_path)
    print(f"Scouting report saved to: {pdf_path}")




def run_pdf_generation(hitter_id, pitcher_id):
    print("Generating scouting report...")

    hitter_name = fetch_player_name(hitter_id)
    pitcher_name = fetch_player_name(pitcher_id)

    if not hitter_name or not pitcher_name:
        print(f"Failed to fetch names for Hitter ID: {hitter_id} or Pitcher ID: {pitcher_id}")
        return

    print(f"Hitter: {hitter_name}, Pitcher: {pitcher_name}")

    # Generate visuals
    hitter_visuals = generate_hitter_season_stats_visual(hitter_id)
    hitter_splits_visuals = generate_hitter_splits_visual(pitcher_id, hitter_id)
    pitcher_arsenal_visuals = generate_pitch_arsenal_visual(pitcher_id)
    pitcher_heatmap_visuals = generate_pitcher_heatmap_visual(pitcher_id, hitter_id)
    pitcher_season_stats_visual = generate_season_stats_viz(pitcher_id)

    if not all([hitter_visuals, hitter_splits_visuals, pitcher_arsenal_visuals, pitcher_heatmap_visuals]):
        print("Failed to generate one or more visuals.")
        return

    visuals = {
        "Hitter Season Stats": hitter_visuals["hitter_stats_fig"],
        "Pitcher Season Stats": pitcher_season_stats_visual,
        "Hitter Splits Against Arsenal": hitter_splits_visuals["hitter_splits_table"],
        "Pitcher Arsenal": pitcher_arsenal_visuals["usage_rate"],
        "Pitcher Heatmap": pitcher_heatmap_visuals,  # Dictionary of heatmaps per pitch type
    }

    pdf_path = "/Users/joshsteckler/PycharmProjects/baseball-mvp/scouting_reports/scouting_report.pdf"
    generate_scouting_report(hitter_name, pitcher_name, visuals, pdf_path)
    print("Scouting report generation complete.")

if __name__ == "__main__":
    hitter_id = input("Enter Hitter ID: ")
    pitcher_id = input("Enter Pitcher ID: ")
    run_pdf_generation(hitter_id, pitcher_id)